spring.application.name=tierheim

server.port=8085
spring.datasource.url: jdbc:mysql://bszw.ddns.net:3306/bfi2427a_tierheim?useSSL=false&serverTimezone=UTC
spring.datasource.username: bfi2427a
spring.datasource.password: geheim
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.adress=0.0.0.0
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
springdoc.swagger-ui.path=/swagger
