spring.application.name=tierheim

server.port=8085
spring.datasource.url: jdbc:postgresql://localhost:5432/thWenApp
spring.datasource.username: postgres
spring.datasource.password: geheim
# Zum Debuggen hilfreich, so werden die SQL-Befehle von Hibernate auf der Konsole ausgegeben
spring.jpa.show-sql=true
# damit Hibernate die Tabellen autpmatisch aus den Entities erzeugt
spring.jpa.hibernate.ddl-auto=update
# Nicht zwingend notwendig - da es nur auf meinem Rechner lokal läuft
server.address=0.0.0.0
springdoc.swagger-ui.path=/swagger